name: pkgdown

on:
  push:
    branches: [main, master]
  workflow_dispatch:

# required for Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          # Installs pkgdown + your package + its deps; also installs system reqs
          extra-packages: any::pkgdown, local::.
          needs: website

      # Build site into ./docs (pkgdown knows we're on Pages)
      - name: Build site
        shell: Rscript {0}
        run: pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE)

      # Upload ./docs as the Pages artifact
      - name: Upload site
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
